### ISSUE TITLE
Cursor pointer missing on some elements

### ISSUE THREAD

**Issue by ricokahler** [sanity-io/design#539]
Hopefully, this is a quick one, but I noticed some elements don't have `cursor: pointer`.

So far I've seen this missing from the button, menu, and checkbox elements.

**Comment by mariuslundgard** [comment]
Hey @ricokahler – that’s actually a feature :-)

It’s a long discussion, and there are not really any good arguments for/against in this thread (except the UX argument):
https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default

Sanity UI attempts to be OS-like, and behave more like an application than a website. So only elements that have `href="..."` will get a `cursor: pointer`, since that is the system default.

I’m open to good arguments for/against, tho!
